config/routes.rb
Friendcircle::Application.routes.draw do
  resources :circles

  root to: "users#new"

  resources :users, only: [:create, :new, :edit, :index]
  resource :session, only: [:create, :new, :destroy]

  resources :posts, only: [:create, :new, :destroy, :index]

end

app/models/circle.rb
# == Schema Information
#
# Table name: circles
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  title      :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Circle < ActiveRecord::Base
  validates :title, :user_id, presence: true

  belongs_to :user

  has_many :circle_user_memberships

  has_many :friends,
  through: :circle_user_memberships,
  source: :user

  has_many :circle_post_shares
  has_many :posts, through: :circle_post_shares
end

app/models/circle_post_share.rb
# == Schema Information
#
# Table name: circle_post_shares
#
#  id         :integer          not null, primary key
#  circle_id  :integer
#  post_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class CirclePostShare < ActiveRecord::Base
  belongs_to :circle
  belongs_to :post
end

app/models/circle_user_membership.rb
# == Schema Information
#
# Table name: circle_user_memberships
#
#  id        :integer          not null, primary key
#  circle_id :integer
#  user_id   :integer
#

class CircleUserMembership < ActiveRecord::Base

  belongs_to :user

  belongs_to :circle

end

app/models/link.rb
# == Schema Information
#
# Table name: links
#
#  id         :integer          not null, primary key
#  url        :string(255)
#  post_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Link < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  body       :text
#  created_at :datetime
#  updated_at :datetime
#  user_id    :integer
#

class Post < ActiveRecord::Base
  belongs_to :user

  has_many :links

  has_many :circle_post_shares
  has_many :circles, through: :circle_post_shares
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string(255)
#  password_digest :string(255)
#  token           :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#

class User < ActiveRecord::Base
  validates :email, :password_digest, :token, presence: true
  validates :token, uniqueness: true
  has_secure_password validations: false

  has_many :circles,
  through: :circle_user_memberships,
  source: :circle

  has_many :circle_user_memberships



  def reset_token!
    self.token = SecureRandom.urlsafe_base64(16)
    self.save
    self.token
  end

  def to_s
    email
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #private

  helper_method :signed_in?, :sign_in, :sign_out, :current_user

  def current_user
    return nil unless session[:token]
    @current_user = User.find_by_token(session[:token])
  end

  def sign_in
    @user.reset_token!
    session[:token] = @user.token
  end

  def sign_out
    current_user.reset_token!
    session[:token] = nil
  end

  def signed_in?
    !!current_user
  end

end

app/controllers/circles_controller.rb
class CirclesController < ApplicationController
  before_action :set_circle, only: [:show, :edit, :update, :destroy]


  def index
    @circles = current_user.circles
  end


  def show
    #@circle = Circle.find(params[:id])
  end

  def new
    @circle = Circle.new
  end

  def edit
    #@circle = Circle.find(params[:id])
  end

  def create
    @circle = Circle.new(circle_params)
    @circle.friends = User.where(id: user_ids)
    @circle.user = current_user
    @circle.save
    respond_to do |format|
      if @circle.save
        format.html { redirect_to @circle, notice: 'Circle was successfully created.' }
        format.json { render action: 'show', status: :created, location: @circle }
      else
        format.html { render action: 'new' }
        format.json { render json: @circle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /circles/1
  # PATCH/PUT /circles/1.json
  def update
    @circle.friends = User.where(id: user_ids)
    respond_to do |format|
      if @circle.update(circle_params)
        format.html { redirect_to @circle, notice: 'Circle was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @circle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /circles/1
  # DELETE /circles/1.json
  def destroy
    @circle.destroy
    respond_to do |format|
      format.html { redirect_to circles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_circle
      @circle = Circle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def circle_params
      params.require(:circle).permit(:title)
    end

    def user_ids
      return [] if params[:users].nil?
      params.require(:users).require(:user_ids)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new

  end

  def create
    @post = Post.new(post_params)
    #has body
    @post.user = current_user
    @post.links.new(link_data)

    @post.circles.new(circle_data)

    if @post.save

      redirect_to posts_url
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end

  end

  def destory

  end

  private
  def post_params
    params.require(:post).permit(:body)
  end

  # extract out submission info from form and make link objects for post
  def link_data
    params.permit(links: [:url])
      .require(:links)
      .values
  end

  def circle_data
     params.permit(circle: [:id]).require(:circle).values
  end


  # def
  #   return [] if params[:users].nil?
  #   params.require(:users).require(:user_ids)
  # end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(email: params[:user][:email])
    .try(:authenticate, params[:user][:password])

    if @user
      sign_in
      redirect_to root_path
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(user_params)
    @user.reset_token!

    if @user.save
      sign_in
      redirect_to root_path
    else
      flash.now[:errors] = @user.errors.full_messages
      redirect_to root_path
    end

  end

  def new
    @user = User.new
  end

  def edit

  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/circles_helper.rb
module CirclesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/circles/_form.html.erb
<%= form_for(@circle) do |f| %>
  <% if @circle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@circle.errors.count, "error") %> prohibited this circle from being saved:</h2>

      <ul>
      <% @circle.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <% User.all.each do |user| %>
      <label> <%= user %>
       <input
       type="checkbox"
       name="users[user_ids][]"
       value="<%= user.id %>">
     </label>
    <% end %>
  </label>

  </div>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/circles/edit.html.erb
<h1>Editing circle</h1>

<%= render 'form' %>

<%= link_to 'Show', @circle %> |
<%= link_to 'Back', circles_path %>

app/views/circles/index.html.erb
<h1>Listing circles</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @circles.each do |circle| %>
      <tr>
        <td><%= circle.user %></td>
        <td><%= circle.title %></td>
        <td><%= link_to 'Show', circle %></td>
        <td><%= link_to 'Edit', edit_circle_path(circle) %></td>
        <td><%= link_to 'Destroy', circle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Circle', new_circle_path %>

app/views/circles/new.html.erb
<h1>New circle</h1>

<%= render 'form' %>

<%= link_to 'Back', circles_path %>

app/views/circles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @circle.user %>
</p>

<p>
  <strong>Title:</strong>
  <%= @circle.title %>
</p>

<p>
  <strong>Friends</strong>
  <% @circle.friends.each do |friend| %>
  <%= friend %>
  <% end %>
</p>

<%= link_to 'Edit', edit_circle_path(@circle) %> |
<%= link_to 'Back', circles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Friendcircle</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= flash[:errors] %>

<% if signed_in? %>
Welcome, <%= current_user.email%>
<%= button_to 'Sign Out', session_url, method: :delete %>
<% else %>
<%= link_to 'Log In', new_session_url%>
<% end %>

<%= yield %>

</body>
</html>

app/views/posts/new.html.erb
<form action="<%= posts_url %>" method="post">

  <input type="hidden" name="authenticity_token"
  value="<%= form_authenticity_token %>">

  <label>Body
    <input type="text" name="post[body]">
  </label>
  <div>
  <label>Links
    <% 3.times do |i| %>
    <input type="text" name="links[<%=i%>][url]">
    <% end %>
  </label>
  </div>

  <div>
  <label>Circles
    <% Circle.all.each_with_index do |circle, i| %>

     <label> <%= circle.title %>
      <input
      type="checkbox"
      name="circle[<%= i %>][id]"
      value="<%= circle.id %>">
    </label>

    <% end %>
  </label>
  </div>

  <div>
  <input type="submit" value="Submit Post">
  </div>

</form>

app/views/users/new.html.erb
<h3>NEW USER!!!!!</h3>

<form action="<%= users_url %>" method="post">

    <input type="hidden" name="authenticity_token"
    value="<%= form_authenticity_token %>">

  <label>Email
    <input type="text" name="user[email]">
  </label>

  <label>Password
    <input type="password" name="user[password]">
  </label>

  <input type='submit' value='Sign Up'>

</form>